---
title: "Implementing a multicentre data bank for trauma surveillance and research"
csl: american-medical-association.csl
output:
  bookdown::html_document2:
    number_sections: false
  bookdown::word_document2:
  bookdown::pdf_document2:
    number_sections: false
    toc: false
    keep_tex: yes
link-citations: yes
bibliography: OTDB.bib
---


**Institutional review board application, an Open Trauma Data Bank collaborative draft**

# Contributors 

*Please add your name and email here*

Martin Henriksson, martin.henriksson@stud.ki.se

Martin Gerdin Wärnberg, martingerdin@gmail.com

Monty Khajanchi, monta32@gmail.com

# Background 

Trauma is a glaring threat to public health globally, resulting in millions of deaths each year [@Naghavi2017]. The World Health Organization (WHO) estimates that more people die from trauma than from malaria, tuberculosis, HIV/AIDS and maternal mortality combined. Almost 90% of trauma deaths have been found to occur in low- and middle-income countries. A majority of these deaths are due to road traffic injuries, primarily affecting those aged 19-29, making traumatic injuries the leading killer of young people globally [@WHO2014].

Whereas the number of deaths due to trauma is substantial, the incidence of non-fatal trauma is also considerable with almost half a billion cases annually globally [@James2018]. As trauma (both fatal and non-fatal) disproportionately affects the young, it therefore affects the working population in a country to a large degree, leading to a considerable loss of work days. Furthermore, trauma in many cases also leads to psychiatric problems, PTSD and PTSD-like symptoms. This further compounds the blow caused by traumatic injuries to the already heavily affected workforce [@Kessler1995].

A substantial body of research indicates that the implementation of trauma systems may substantially reduce trauma mortality [@Nathen2000; @Lansink2007]. A trauma system (depending on its design) may be implemented to improve a specific part of the trauma care, such as pre-hospital care or registration of patients. Trauma systems have previously been implemented successfully: In 2007 a publication revealed a large portion of trauma patients in the United Kingdom (UK) received substandard trauma care [@NCEPOD2007]. In response to this several trauma networks i.e. trauma systems were implemented, which significantly improved trauma outcome in terms of mortality [@Lockey2018].

One of the most important components of trauma systems is a trauma registry, or a trauma data bank [@Beuran2014]. The data bank is used to track trauma patients and their outcomes to facilitate trauma surveillance and research. Towards Improved Trauma Care Outcomes (TITCO), Swedish Trauma Registry (SweTrau) and National Trauma Data Bank (NTDB) are examples of registries currently in use. All of these have been used in trauma research, contributing to clinical guidelines and improved patient care - and ultimately to reduced trauma mortality and morbidity [@TITCO2019; @SweTrau2019; @NTDB2019].

This project proposes to implement a trauma data bank at [REPLACE WITH CENTRE NAME], with the aim to collect the absolute latest available trauma data for use in research or institutional quality improvement programs.

# Methods 

## Design 
Data bank implementation.

## Setting 

Hospitals that receive trauma patients.

## Participants 

**Eligibility criteria**

Patients who present to the emergency department of participating hospitals with history of trauma. History of trauma is defined as having any of the International Classification of Diseases version 10 external causes of morbidity and mortality, codes V01-Y36, as reason for presenting.

**Sources and methods of selection of participants**

Participants will be enrolled and data will be collected by dedicated research officers who work five eight hour shifts per week according to a rotating schedule so that morning, evening and nights shifts are covered. The project officers will approach potential participants for enrollment during their emergency department stay. In addition to this the project officers will collect data of all patients with burns as the mechanism of injury (ICD codes X00-X19, X75-X77, X96-X98) and admitted anytime in the day irrespective of their shift.

**Methods of follow up**

Participants will be followed up at the emergency department or on hospital discharge and at 24 hours, 30 days, 6 months, and 12 months. If a participant is still admitted he or she will be followed up in person, otherwise there will be telephone follow ups.

## Variables 

-	All-cause mortality at discharge, 24 hours, 30 days, 6 months and 12 months after arrival to participating hospital
-	Date and time of death, up until 12 months after arrival to participating hospitals
-	Health related quality of life
-	Return to work
-	Demographic variables
-	Mechanism of injury
-	Vital signs
-	Comorbidities
-	Investigations
-	Injury descriptions
-	Burns specific data like TBSA with depth of burns, inhalational burns, household burns etc

## Data sources 

Vital signs will be recorded by the project officers using hand held equipment when participants arrive to the emergency department. Demographics and follow up will be collected from participants, participant parties, and hospital records. Procedure data will be collected from hospital health care providers and hospital records.

## Ethical considerations

This data bank will be implemented and maintained following the four core principles of medical ethics, i.e. respect for autonomy, non-maleficence, beneficence, and justice. 

**Respect for autonomy**

Patients included in the trauma data bank will receive a letter detailing the purpose and procedures. They are informed that participation is voluntary, and that they may withdraw at any time regardless of reason.

**Non-maleficence**

Patient data leakage and patient identification are the most significant risks to the patient population. The data collected will be stored in a locked cabinet to which only relevant personal has access. When data is transferred, all secondary storage devices (e.g. hard drives) will be password protected and encrypted. These actions will be undertaken to minimize these risks to the patient population.

**Beneficence**

The intention of this data bank is to provide data for future research and quality improvement in the field of trauma and trauma care. This research will in turn hopefully improve trauma outcomes by improving trauma patient care and trauma patient management.

**Justice**

All patients included in this study were treated regardless of age, sex, or prior medical history. Patients received the same level of care whether they choose to participate in the data bank or not.

## Data management 

Project officers will first capture data on paper case record forms. These forms will be archived in a locked cabinet at the centre to which only the principal investigator and the project officers have access. The forms will be archived for as long as required by national and local rules and regulations require. Data will then be transferred from the paper case record forms to a digital database. A database with patient identifiers will be kept locally on the project officers and principal investigators' hard drives. This database will be encrypted and password protected. The project officers will update the digital database after each follow up. With regular intervals the database will be de-identified locally. In de-identification process all patient and centre identifiers will be removed. The 
de-identified database will then be merged with databases from other centres that also have implemented a data bank using the same system. This merged de-identified database will then be available in an open public repository, called the Open Trauma Data Bank. Use of the de-identified database for any purpose will be subject to a license that prohibits any attempt at re-identification of patients or centres.

# References 

<div id="refs"></div>

[Add centre name and address]

# PATIENT INFORMATION SHEET 

This centre has implemented a trauma data bank. Before your data can be included in this data bank the purpose of the data collection must be explained to you, and you must be given the chance to ask questions. Please read carefully the information provided here. If you agree to participate, please sign the informed consent form. You will be given a copy of this document to take home with you.

**Title:**

Principal Investigator(s):	[Add investigator name] 

**PURPOSE**

We are currently collecting data in this hospital to be included in an institutional trauma data bank. The purpose of this data bank is to provide quality data, which will be used for research that aims to improve care and outcome of trauma patients. We ask you to participate in this data bank because you present to this hospital after having an injury.

**STUDY PROCEDURES AND VISIT SCHEDULE**

If you agree to participate, we will:

* Store health data registered in your hospital record and vital signs recordings from the emergency department
* Contact you in person or by telephone for follow ups to obtain information about your health status at the following times:

    - On arrival at the emergency department
    - On hospital discharge
    - 24 hours after discharge
    - 30 days after discharge
    - 6 months after discharge
    - 12 months after discharge

When you arrived at the hospital, we recorded some basic parameters such as your age, gender, and how you were injured. We also recorded health data such as blood pressure, heart rate, and body temperature. If you want complete information regarding all the parameters that were recorded, please do not hesitate to ask, and we will be happy to inform you. Should you wish that your data is deleted from data bank at this hospital, please contact us using the contact information provided below. The data bank may be used for research that can be published as scientific articles; however, it will not be possible to identify you by reading any article that may result from this data bank. Further, data from this project will be combined with data from other hospitals that use the same system and shared for other researchers and individuals to use, but it will not be possible to identify you using that data.

**WITHDRAWAL FROM STUDY**

Participation in this data bank is completely voluntary. Even if you agree to participate now you are free to withdraw at any time without giving any reason for doing so. Withdrawing will not affect your ordinary treatment or the care given to you. To withdraw contact any of the contact persons using the contact information provided. Note that we can only delete data from the data bank in this hospital. We cannot delete data once it has been de-identified because we will not be able to tell from whom the data came.

**POSSIBLE RISKS, DISCOMFORTS AND INCONVENIENCES**

We have not been able to identify any major risks associated with participating in this study. Should there be any inconveniences you are free to withdraw at that point, or at any time using the contact information provided.

**POTENTIAL BENEFITS**

The data bank will be used for research and quality improvement that may help to improve the care of injured patients. Although this project will not affect the care you are given in this hospital at this time, your participation will contribute to medical knowledge, and may improve care for others that are injured.

**SUBJECT'S RIGHTS**

Your participation in this study is entirely voluntary. Your questions will be answered clearly and to your satisfaction. In the event of any new information becoming available that may be relevant to your willingness to continue in this study, you will be informed in a timely manner by the Principal Investigator or his/her representative.

**CONFIDENTIALITY OF STUDY AND MEDICAL RECORDS**

The results of this research may be published as a scientific article; however, it will not be possible to identify you by reading any article that may result from this work. Further, data from this project will be combined with data from other hospitals that use the same system and shared for other researchers and individuals to use, but it will not be possible to identify you using that data.

Also, Regulatory Agencies, Institution Review Board and Ministry of Health will be granted direct access to your original medical records to check study procedures and data, without making any of your information public. By signing the Informed Consent Form attached, you are authorizing such access to your study and medical records.

**COSTS OF PARTICIPATION**

No charge will be levied on you if you take part in this project. You will not receive any compensation for participating in this project.

**RESEARCH RELATED INJURY AND COMPENSATION**

Due to the observational nature of this project, it is unlikely to cause any research related injury. The hospital will provide medical care for any problems that may arise during this study.

**WHO TO CONTACT IF YOU HAVE QUESTIONS?**

If you have questions regarding this project and your rights, or in the case of any injuries sustained during this project, you may contact the Principal Investigator:

[Add study contact information]

# CONSENT FORM

**Protocol Title:** Institutional Trauma Data Bank

**Subject's Particulars**

Name:                                         	              	

NRIC/PNR/SSN No.:


Address:


Date of birth _______________ dd/mm/yyyy	

Phone No:

Phone number(s) to your relatives or friends that you agree we may contact if you do not answer your phone:

> Part I- to be filled by patient

I, _________________ (Pt ID No._________________) Agree / do not agree to participate in the project as described and, on the terms detailed in the Patient Information Sheet. The nature of my participation in the proposed project has been explained to me in ____________________ by Dr/Mr/Ms ____________________. I have fully discussed and understood the purpose and procedures of this project. I have been given the Patient Information Sheet and the opportunity to ask questions about this project and have received satisfactory answers and information. I understand that my participation is voluntary and that I am free to withdraw at any time, without giving any reasons and without my medical care being affected. I also give permission for information in my medical records to be used for this project. In any event of publication and sharing of the data with other researchers and individuals, I understand that this information will not bear my name or other identifiers and that due care will be taken to preserve the confidentiality of this information.



____________________ [Signature/Thumbprint (Right / Left) of patient]


____________________ (Date of signing)


> Part II- to be filled by parent / legal guardian, where applicable

I, ____________________ hereby give consent for the above patient to participate in the proposed project. The nature, risks and benefits of the study have been explained clearly to me and I fully understand them.

____________________ [Signature/Thumbprint (Right / Left) of parent /legal guardian]

____________________ (Date of signing)

> Part III- to be filled witness, where applicable

An impartial witness should be present during the entire informed consent discussion if a subject or the subject's legally acceptable representative is unable to read. After the written informed consent form and any written information to be provided to subjects, is read and explained to the subject or the subject's legally acceptable representative, and after the subject or the subject's legally representative has orally consented to the subject's participation in the study and, if capable of doing so, has signed and personally dated the consent form, the witness should sign and personally date the consent form.
		
____________________ (Name of witness)			

____________________ (Designation of witness)

____________________ (Signature of witness)		

____________________ (Date of signing)